### ISSUE TITLE
Stack overflow exception when serializing an exception with a Type object in data

### ISSUE THREAD

**Issue by jdextraze** [MindscapeHQ/raygun4net#240]
This is using the log4net.Raygun nuget package but the problem comes from Raygun4Net 4.2.1.

This test use NUnit and FluentAssertions.

```
Action when = () =>
{
	BasicConfigurator.Configure(new RaygunAppender
	{
		ApiKey = "===YOUR=API=KEY===",
		Threshold = Level.Error
	});

	var exception = new Exception();

	exception.Data.Add("Type", typeof(Exception)); // This make it crash

	LogManager.GetLogger("Test").Error(exception);

	Thread.Sleep(10000); // Wait for Raygun task to run
};

when.ShouldNotThrow(); // The test runner will crash here
```

**Comment by QuantumNightmare** [comment]
Thanks for pointing this out. I have not been able to reproduce the stack overflow exception though - Raygun4Net 4.2.1 is supposed to be able to detect cyclic object structures (Such as those that occur in the Type object) when serializing the message.

Regardless, I would not recommend sending an entire Type object as custom data to Raygun. The reason being that Raygun supports rich custom data serialization meaning that objects within the Exception.Data property, or the UserCustomData dictionary on the RaygunClient will have all their properties included in the serialized message, as well as all properties on any child objects and so on. In the case of a Type object, that means information about the entire application assembly, and all the assemblies used by the application will attempt to be serialized into the Raygun message.

In a future version, we might consider replacing Type objects with strings in the serializer. This would be at least a month away.

For now there are 2 options:

If you can, set the Type value as a string instead of the whole Type object.

If however you require this to be a Type object for part of your application to function, then I would recommend adding a RaygunClient.SendingMessage hook to modify the RaygunMessage object before it is serialized. Here, change any custom data Type objects to be a string instead. That way, you can still use the Type value within your app, but only a string will be sent to Raygun. Here is the documentation for modifying the RaygunMessage before it gets sent: https://raygun.io/docs/languages/net/asp#modify-cancel-message

Please let me know if you have further questions about any of this.

-Jason Fauchelle

**Comment by QuantumNightmare** [comment]
Raygun4Net v5.0.1 which is now available, will now serialize Type objects for you as the fully qualified assembly name, rather than trying to serialize the entire Type object structure.
