### ISSUE TITLE
Request body not logged for owin

### ISSUE THREAD

**Issue by Fnopster** [MindscapeHQ/raygun4net#288]
Hi,

I have a web api project that uses owin. In the startup, it attaches raygun logging via: `RaygunWebApiClient.Attach(config)`

The problem is that the request body is not logged to raygun when an error is thrown.

In RaygunWebApiClient.cs, the attach method explicitly excludes RaygunWebApiDelegatingHandler when Owin assembly is detected. This handler is used to extract request body and to store it in request properties. The request body in the properties is then used in the message builder to generate the log.

```
var owinAssembly = AppDomain.CurrentDomain
    .GetAssemblies()
    .FirstOrDefault(a => a.FullName.StartsWith("Owin"));
if (owinAssembly == null)
{
    config.MessageHandlers.Add(new RaygunWebApiDelegatingHandler());
}
```

So, to simplify; it's not generating a log because the handler is been excluded. What's the reason for not adding the handler in owin applicationS? Is there a better way to log request body?

**Comment by gregpakes** [comment]
I would like to know the answer to this too.  It looks like you won't get a request body if you have any assemblies with "owin" in their name.

Why is this?

**Comment by QuantumNightmare** [comment]
Apologies for not replying to this. I remember the issue we ran into is if Owin is involved, the stream that provides the request body can only be read once. When Raygun was reading it to include the body in the report, the body could not be read again which caused problems in the web application itself. Checking for an Owin assembly was thought to be the easiest way to work around this.

I'd like us to revisit this but do not have a time frame of when we'd be able to. At the very least, I'd expect checking CanSeek on the Stream would work and be better than checking for an Owin assembly. In our AspNetCore provider, we still read unseekable streams and then copy the result to a new stream and put that back on the request so that Raygun can still get the body, and other things can still read it. Maybe we'd be able to do that here too.

**Comment by gregpakes** [comment]
Thanks for the response.  Just a side note, I am not using AspNetCore (you mentioned the AspNetCore provider above)

**Comment by gregpakes** [comment]
How quickly could you verify and accept a pull request matching the functionality to the AspNetCore provider?

I can potentially allocate some resources to submitting this.

**Comment by xt0rted** [comment]
Here's my implementation for Raygun.Owin:

https://github.com/xt0rted/Raygun.Owin/blob/148835312e75c87da83490653f9d09e690ed2978/src/Raygun.Owin/Builders/RaygunRequestMessageBuilder.cs#L39-L44

https://github.com/xt0rted/Raygun.Owin/blob/148835312e75c87da83490653f9d09e690ed2978/src/Raygun.Owin/Owin/OwinRequestExtensions.cs#L41-L57

This runs fine if you're using the systemweb host, but if you're self hosting with nowin or httplistener it will throw since those hosts typically don't provide a seekable stream for the request body. The stream provided by systemweb is seekable and is what I've been running this on for the last 5 years or so.

I put together a [proof of concept](https://github.com/xt0rted/Raygun.Owin/tree/seekable-body) stream wrapper to buffer the contents into memory but it never made it past a PR. It worked fine in my testing, but I'm not sure how it'd be in production or under load.

**Comment by gregpakes** [comment]
Hi all - I have submitted a PR for this issue.  The solution looks far too simple so I would encourage further testing.

Having said that - I have replicated the original issue and can confirm that this solution fixes the issue and does not appear to break anything else.

**Comment by mduncan26** [comment]
PR for the issue has been merged. Closing the related issue.
