### ISSUE TITLE
Proposal: RawData should adhere to the sensitive data removal

### ISSUE THREAD

**Issue by gregpakes** [MindscapeHQ/raygun4net#304]
This is a proposal for a PR.  I want to start a conversation first, so I don't write a feature that won't be used.

**The Issue**

In my application, I never want passwords to be logged.  I am using the `ignoreFormFieldNames` option to remove password.  However, we have some API endpoints that also accept password and these are not removed from the RawData.  

**Current Behaviour**

Looking at the source, it looks like the MVC provider will search the raw data for matching fields in the form data that should be ignored.  If they are found, it will remove them.  But, it will not remove them if they are not in the form data (which they won't be for an API call).

**Proposal**

My suggestion is that the RawData should be searched for all ignored items and stripped appropriately.  Alternatively, we could search for just the ignored form data and strip that.

I would appreciate your thoughts.

**Comment by drewwilliams1982** [comment]
I am faced with this issue too. Is there any feedback on Gregs proposal before I can start working on it?

**Comment by turtlespin** [comment]
Hi all,

Thanks for the feedback. While its been a while since this was logged, we agree with wanting to making a change around how this works and what capabilities the provider gives you. 

Currently we provide the SendingMessage event as a "last chance" hook prior to transmission where you have an ability to sanitize or otherwise manipulate the message before its sent to our API so this is a place where you can achieve this but at the cost of having to implement your own logic to handle this.

What we feel should be improved here is you should be able to filter more on a general concern (e.g. passwords) and have it apply across the whole payload if desired (while still allowing for more targeted removal from specific HTTP collections as is currently available). 

We have some resource available to look at this in the near future so I was hoping to get some feedback before we jump into building something out. To help scope this a bit further, are you able to give some examples of how you would be looking to use this, where the data you are looking to remove is actually located in the payload and what data (field name, regex to match on the value) you would anticipate using to look for a match. Happy to discuss this offline if there is some sensitivity to the details.

**Comment by drewwilliams1982** [comment]
Hi Jeremy,

Thanks for the response!

The main issue we have right now is a password being visible. It's part of a simple JSON payload submitted as a POST request to an API endpoint. It's simple enough in structure:
`{ "password": "xxxxx", ... }`

With reference to GDPR, there's likely to be a plethora of similar payloads where there is more structured data and it's in our best interests to redact the information. For example, we do handle sensitive personal information which shouldn't be shared outside our application. In these cases, we'll ideally want to specify the path in the fields in the JSON; what would be cool is an attribute on the C# API model to mark the class or individual fields as redacted.

Thanks,
Andrew

**Comment by gregpakes** [comment]
I just wanted to add my 2 cents here... 

I suspect an attribute as discussed by @drewwilliams1982 would be too application specific to add into the Raygun Library, but my requirements are as follows:

- There is certain data that we *never* want logged, regardless of method (form, querystring, raw data)
- You provide ways to strip data from form fields, but I think this needs expanding to all data.

I suspect the complexity comes when you are looking to strip data from the *body* payload.  I suspect you would need to parse it on some level, but it could be in any format (xml, JSON, key pair etc).

**Comment by QuantumNightmare** [comment]
We've discussed this issue today and so far have the following plan:

* Add an ignore-query-parameters setting to function just like the other ignore-x settings. (to fill in missing but related functionality).
* Add a new setting that takes a list of key strings of sensitive data to ignore everywhere. Any key-value pairs of these keys found in the raw data will be removed, as well as any headers/server-variables/cookies/form-fields/query-parameters from their respective sections of the Raygun payload.
* Removing data from the raw payload will at least support Json data. This will be implemented in a way that you could provide your own custom parser for formats that we don't handle.
* Add an option to ditch the entire raw payload in the case that a specified sensitive data key is found, but failed to remove the value. (not requested in the discussion here, just a safety net we feel could be useful).
* the existing behaviour of the ignore-x features will be unchanged.
* We do not plan to look into the C# attribute approach at this time.

This work is expected to begin within the next 2 weeks. In the meantime, let us know any further feedback you have about this.

**Comment by gregpakes** [comment]
@QuantumNightmare This sounds great!

**Comment by mduncan26** [comment]
Hi all,

Just a quick update to let everyone know this work is currently underway. We will notify everyone soon once the work is complete. 

Cheers,
Mitchell.

**Comment by mduncan26** [comment]
Hi all,

We have now released updates that address filtering sensitive data that comes through when capturing information about the HTTP request that generated a crash report. The following providers have the additional options for filtering request data.

Mindscape.Raygun4Net.AspNetCore (v6.1.0)
Mindscape.Raygun4Net.Mvc (v5.7.0)
Mindscape.Raygun4Net.WebApi (v5.7.0)
Mindscape.Raygun4Net (v5.7.0)

We will be updating our public documentation soon, but in the meantime you can find out more in the readme's of each provider's folder in GitHub.

Thank you for your patience while we completed this work. I will be closing this issue now but feel free to open another or contact us through the Raygun app if you have further questions or concerns.

Regards,
Mitchell.
