### ISSUE TITLE
Request Body not read for Asp.Net Core WebApi

### ISSUE THREAD

**Issue by BradRem** [MindscapeHQ/raygun4net#311]
I've attached a simple project that illustrates Raygun is not able to read the request body for a WebApi call under Asp.Net Core.

In the project, include a valid Raygun API key in appsettings.json and POST a message like this:

```
POST /api/values HTTP/1.1
Host: localhost:50146
Content-Type: application/json
Cache-Control: no-cache

{
	name: "This Test",
	description: "Testing raygun"
}
```

The RAW Request Data will be: "Failed to retrieve raw data: Specified method is not supported."  

[RayGunWebApiTest.zip](https://github.com/MindscapeHQ/raygun4net/files/628379/RayGunWebApiTest.zip)

**Comment by j5alive** [comment]
I've done some initial investigation on why this is happening and it is due to not being able to seek the request stream. When we try to get the raw request data we rewind the request stream to then read it out. This fails with an Exception as the request.Body stream does not allow seek. It looks like we can enable this on the request by calling `request.EnableRewind()` but initial testing indicates we'd need to do this early in the pipeline before the first read of the stream.

https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.AspNetCore/Builders/RaygunAspNetCoreRequestMessageBuilder.cs#L96

**Comment by xt0rted** [comment]
@j5alive this was an issue with Raygun.Owin as well, but not on all hosts. The System.Web host was fine, but the selfhost (which is similar to the kestrel server) wouldn't work. My attempt at working around it was to wrap the incoming stream but it was only used for testing, never made it to production. https://github.com/xt0rted/Raygun.Owin/commit/ef30a34c3a3d88c2630e0cc6094e8f489cdb89ba

**Comment by iluzyanin** [comment]
Just doing `request.EnableRewind()` didn't work for me in case of "application/json" content type of request. `RaygunAspNetCoreRequestMessageBuilder.Build()` method internally tries to read from `request.Form` which throws `NotSupportedException` "Incorrect Content-Type: application/json", since there were no form values actually.
It seems that checking the `request.HasFormContentType` before trying to read form values should fix this.

**Comment by dwolsey** [comment]
Thanks, our code was erroring with NotSupported Exception on this line.

Request.Body.Seek(0, SeekOrigin.Begin);

I added on the line before:

Request.EnableRewind();

And I no longer got the exception.
