### ISSUE TITLE
WebApi HttpResponseExceptions are missing Content

### ISSUE THREAD

**Issue by kblooie** [MindscapeHQ/raygun4net#334]
When throwing HttpResponseExceptions, a common use case is to include a message like so:
`throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest,
                    "Your request is invalid b/c of xxx"));`

It looks like `RaygunWebApiMessageBuilder.SetExceptionDetails(Exception exception)` tries to address this by adding the Content to ex.Data. However, this data is not being included in the RaygunErrorMessage.

This is because `RaygunErrorMessageBuilder.Build(exception);` is being called _before_ the HttpResponseException specific code occurs.

Solution:
Call `RaygunWebApiMessageBuilder.SetExceptionDetails(Exception exception)` after all the ex specific code, at the end of `RaygunWebApiMessageBuilder.SetExceptionDetails(Exception exception)`.

**Comment by kblooie** [comment]
Basing this off of your 5.41 branch:
https://github.com/MindscapeHQ/raygun4net/blob/v5.4.1/Mindscape.Raygun4Net.WebApi/RaygunWebApiMessageBuilder.cs

**Comment by QuantumNightmare** [comment]
Hi kblooie,

Thanks for pointing out this dormant code. Looks like it's been left like that since the very first prototype of WebAPI support - I suspect it must have worked at some point early on.

I've made a PR to capture the response content: https://github.com/MindscapeHQ/raygun4net/pull/337

Rather than putting the content into the Data dictionary of the exception, we've decided to add a new property called "Content" to the existing Response section of the Raygun exception report. Like all the other ex specific code in the SetExceptionDetails method, this Content can be set onto the Response section right then and there.

Similar code has also been added to the RaygunWebApiHttpException which gets sent in place of lost exceptions that get swallowd behind WebAPI bad status codes occurring in controller actions. The response content can be captured and sent here in the same way. These may have come from HttpResponseExceptions specifically, but we'll be capturing the response content from any bad status code that comes through here and sending it which should be useful.

**Comment by QuantumNightmare** [comment]
Hi kblooie,

Raygun4Net.WebApi can now include the response content with exception reports where possible in version 5.5. Please note that by default, Raygun will not read the response content in order to avoid any potential security issues with suddenly reporting data that it previously did not. In order to capture response content in your exception reports, you'll need to set the isResponseContentIgnored config setting to false.

As mentioned, this is placed on a new "Content" field on the existing Response section of the report payload. Currently this can only be viewed in the "Raw data" tab of a report viewed in Raygun, but later we can display this within the Http tab with the ability to 'star' it on to the Summary tab.
