### ISSUE TITLE
Proposal: increase length limitation on HTTP request rawdata

### ISSUE THREAD

**Issue by trevorloflin** [MindscapeHQ/raygun4net#354]
In the `RaygunAspNetCoreRequestMessageBuilder` class, the length of the RawData field is artificially limited to 4096 characters: https://github.com/MindscapeHQ/raygun4net/blob/c2d7992fe6bccd64c6104cb9664278d70a6deb66/Mindscape.Raygun4Net.AspNetCore/Builders/RaygunAspNetCoreRequestMessageBuilder.cs#L112

Can that number be increased (perhaps to 65536)?

**Comment by CmdrKeen** [comment]
Hi Trevor,

While not a big issue in itself, we do limit Raygun messages to 128kb. If we changed this for everyone, it would be a breaking change since many folks manage their message size to fit so having an update blow out the size of the RawData field would potentially have their messages now get rejected for being too large.

Couple of ideas:

1. Append more data to the CustomData property. You may choose to attach the next 50k if it's valuable to you.
2. We could look at making it configurable, maintaining the current default
3. (not recommended) would be to fork the provider and use a custom value

Hope that helps!

**Comment by trevorloflin** [comment]
Making the number configurable sounds like a proper compromise to me. Maybe an optional "RequestRawDataMaxSize" field that defaults to 4096 if missing.

**Comment by mduncan26** [comment]
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.
