### ISSUE TITLE
Mindscape.Raygun4Net.WebApi NuGet package should have a dependency on Mindscape.Raygun4Net

### ISSUE THREAD

**Issue by spongessuck** [MindscapeHQ/raygun4net#363]
I was following the setup instructions for Raygun for .NET WebApi and it only mentioned needing the Mindscape.Raygun4Net.WebApi NuGet package, which I was able to install on its own, but when I tried to use RaygunWebApiClient.Attach, Visual Studio said that I needed an assembly reference to Mindscape.Raygun4Net.

Currently, the only dependency Mindscape.Raygun4Net.WebApi lists is Mindscape.Raygun4Net.Core, which seems to not be enough to use the package.

**Comment by QuantumNightmare** [comment]
Hi spongessuck,

I have tried this out now just to make sure, and find that installing the Mindscape.Raygun4Net.WebApi project (Which also installs Mindscape.Raygun4Net.Core due to dependency) compiles and reports exceptions as expected.

The message from Visual Studio would be referring to the Mindscape.Raygun4Net namespace within the Mindscape.Raygun4Net.Core package. Apologies for the confusion in naming here.

I'm not sure what would cause this message though, unless the .Core package failed to install or appear as a reference in the project (it appears as Mindscape.Raygun4Net in the references list). Please let us know more about your project(s) setup such as project types and versions if this is still not working for you.

-Jason Fauchelle
