### ISSUE TITLE
Mindscape.Raygun4Net.Mvc dependency issue

### ISSUE THREAD

**Issue by kendaleiv** [MindscapeHQ/raygun4net#364]
[Mindscape.Raygun4Net.Mvc](https://www.nuget.org/packages/Mindscape.Raygun4Net.Mvc) `5.5.2` depends on [Mindscape.Raygun4Net.Core](https://www.nuget.org/packages/Mindscape.Raygun4Net.Core) `>= 5.5.2` which does not exist on NuGet currently.

**Comment by QuantumNightmare** [comment]
Hi kendaleiv,

Version 5.5.2 of Mindscape.Raygun4Net.Core has been marked as not listed. Installing Mindscape.Raygun4Net.Mvc via the Visual Studio NuGet add on or the package manager console will resolve the dependency. If not, you may need to update your NuGet add on as there was a version that had a bug preventing non-listed dependencies from being resolved (hence why some versions of the core package were listed).

Let me know if you are using a different method of installing the packages, or if my above comments don't help. If we need to, we can mark the core package as listed. Ideally we'd keep it (and all older versions) as not-listed to avoid confusion between this and the .NET core package, and because the core package can not be used by itself.

-Jason Fauchelle

**Comment by kendaleiv** [comment]
OK, thanks! Closing.
