### ISSUE TITLE
WebApi nuget >= 5.5.0 breaks chunked upload

### ISSUE THREAD

**Issue by danmusk** [MindscapeHQ/raygun4net#368]
I have spent some time investigating why we suddenly got 500 internal server errors for file-uploads from our Cordova mobile apps. The exception logged in RayGun says:

`System.InvalidOperationException: Either BinaryRead, Form, Files, or InputStream was accessed before the internal storage was filled by the caller of HttpRequest.GetBufferedInputStream.`

I managed to recreate the issue with an integration test using HttpClient and setting `TransferCodingHeaderValue("chunked")`, as Chunked-mode defaults to true for the [Cordova-file-plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file-transfer/index.html#upload). Uploading files non-chunked (not setting any TransferCodingHeader) is not showing any problems. 

When I downgrade the Mindscape.Raygun4Net.WebApi Nuget to version 5.4.1 chunked upload is working again. When I upgrade to 5.5.0 or 5.5.2 it is not working, throwing the exception above. Mindscape.Raygun4Net.Core Nuget can be version 5.5.0 and things still work. So it seems that it is the WebApi Nuget that is the problem.

Any idea what is happening here? I can provide more code and details if needed.

**Comment by QuantumNightmare** [comment]
Hi danmusk,

Looking at that exception message, the only things that Raygun4Net use directly is 'Form' and 'InputStream'. Though, these are used by the Raygun4Net assembly, not Raygun4Net.WebApi. Something that change in 5.5.0 is the way we read the raw request content, perhaps this is responsible: https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.WebApi/RaygunWebApiDelegatingHandler.cs

With Raygun4Net 5.5.0 or higher installed, you could try remove the RaygunWebApiDelegatingHandler HttpConfiguration.MessageHAndler collection. Basically reversing the following line: https://github.com/MindscapeHQ/raygun4net/blob/master/Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs#L139

The other change is the ability to include the response in the Raygun report. By default, we don't read the response, so unless your setting IsResponseContentIgnored to false, this won't be related. If you are setting it to false, see what happens if you don't set it.

-Jason Fauchelle

**Comment by danmusk** [comment]
Hi Jason,

Thanks for a quick response. After a test, removing the RaygunWebApiDelegatingHandler fixes the issue mentioned above with v.5.5.x. Here is what I did:
- Chunked upload working (Raygun v.5.4.1)
- Update Nuget, from 5.4.1 to 5.5.2 (Mindscape.Raygun4Net.Core and Mindscape.Raygun4Net.WebApi)
- Chunked upload now fails
	- Either BinaryRead, Form, Files, or InputStream was accessed before the internal storage was filled by the caller of HttpRequest.GetBufferedInputStream.
- In WebApiConfig, remove the RayGunHandler
	var raygunHandler = config.MessageHandlers[0];
	config.MessageHandlers.Remove(raygunHandler);
- Chunked upload is now working again

I have not used the IsResponseContentIgnored anywhere.

**Comment by QuantumNightmare** [comment]
Hi danmusk,

Thanks for trying that out. I'm not sure if we can do anything about detecting this issue on a per-request basis - ideally without needing to bring in any dependencies. What we should do at least though in a future release is to use the IsRawDataIgnored setting to skip all the code in the delegating handler. This would give you more convenient control over this issue rather than needing to 'hack' out the delegating handler. I do not have a time frame of when this will be released though sorry. Most likely not until the new year.

-Jason Fauchelle

**Comment by danmusk** [comment]
Looks like this has been resolved in version 5.6.

**Comment by mduncan26** [comment]
Closing this issue as it is reported as resolved.
